#include <stdlib.h>
#include <stdio.h>

char *p;
char *begin, *after_end;

void print_banner() {
	printf("\n");
	printf("################################################\n");
	printf("###  Welcome to Vinit's Brain Fuck compiler  ###\n");
	printf("################################################\n");
	printf("\n");
}

void initialize() {
	p = (char*)malloc(30000);
	begin = p;
	after_end = begin + 30000;
	return;
}

void pp() {
	printf("[pointer] ==> 0x%x\n", *p);
}

void p_debug(int till) {
	int j;
	printf("DEBUG array value print => [");
	for (j = 0; j < till; ++j) {
		printf("0x%x ", begin[j]);
	}
	printf("]\n");
	return;
}

char* match_ending_sq_bracket(char* ccp) {
	if (*ccp != '[')
		return ccp;
	// ccp is the pointer to the initial opening square bracket '['
	// num_sq is the number of nested square brackets currently the code is in, inside the initial square brackett code block
	int num_sq = 0;

	// go inside the square bracket scope
	++ccp;

	while (*ccp != '\0') {
		if (*ccp == ']') {
			if (num_sq == 0) {
				return ccp;
			} else if (num_sq > 0){
				--num_sq;
			}
		} else if (*ccp == '[') {
			++num_sq;
		}
		++ccp;
	}
	return ccp;
}

int process_code(char* input_code, int inside_sq) {
	// inside_sq is 1, if the code is in a square bracket. 0 means its not inside any square bracket

	// ccp is for the "current code pointer" in the bf input code
	char* ccp = input_code;

	while(*ccp != '\0') {
		switch (*ccp) {
			case '>':
				++p;
				if (p == after_end) {
					printf("Pointer went out of 30000 byte Limit.\nWent too right.\nExiting.\n");
					return -1;
				}
				break;
			case '<':
				--p;
				if (p == begin - 1) {
					pp();
					p_debug(12);
					printf("Pointer went out of 30000 byte Limit.\nWent too left.\nExiting.\n");
					return -1;	
				}
				break;
			case '+':
				++*p;
				break;
			case '-':
				--*p;
				break;
			case '.':
				putchar(*p);
				break;
			case ',':
				*p = getchar();
				break;
			
			case '[':
				// if the value of "the pointer" is not zero, i.e.. *p != 0, then go on with you you regular life to see the next code
				if (*p) {
					if (process_code(ccp + 1, 1) == -1)
						return -1;
				}
				ccp = match_ending_sq_bracket(ccp);
				break;
				
			case ']':
				if (inside_sq) {
					if (*p) {
						ccp = input_code - 1;
					} else {
						return 0;
					}
				}
				// if found a closing sq bracet ']' without any opening sq bracket, then just ignore it.
				break;
			
			default:
				break;
		}
		++ccp;
	}
	return 0;
}

int main(int argc, char *argv[]) {
	char *usage = "Usage: ./bfc <filename.bf>";
	
	char * buffer = 0;
	long length;

	// printf("%i\n", argc);
	if (argc >= 2) {
		char *file_name = argv[1];
		// printf("%s\n", file_name);
		FILE *f;
		f = fopen(file_name,"r"); // read mode

		if( f == NULL )
		{
	    	perror("Error while opening the file. Please Check the file and Try Again.\n");
	    	exit(EXIT_FAILURE);
	   	}

	   	if (f)
		{
			fseek (f, 0, SEEK_END);
			length = ftell (f);
			fseek (f, 0, SEEK_SET);
			buffer = malloc (length);
			if (buffer)
			{
				fread (buffer, 1, length, f);
			}
			fclose (f);
		}

	} else {
		printf("%s\n", usage);
	}

	if (!buffer)
	{
		// buffer = "++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+...>.";
		buffer = "";
		print_banner();
	}

	char *input_code = buffer;
	// printf("%s\n", input_code);

	

	// prints the number value on the first cell, after initialing it to 165
	// char *input_code = ">+++++++++++[-<+++++++++++++++>] # initialize 165 at first cell>++++++++++<<[->+>-[>+>>]>[+[-<+>]>+>>]<<<<<<]>>[-]>>>++++++++++<[->-[>+>>]>[+[-<+>]>+>>]<<<<<]>[-]>>[>++++++[-<++++++++>]<.<<+>+>[-]]<[<[->-<]++++++[->++++++++<]>.[-]]<<++++++[-<++++++++>]<.[-]<<[-<+>]";
	
	// prints the number value on the first cell, after initialing it to 165, does the same thing but this code is generated by some other code
	// char *input_code = ">>>>>>>>>+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[<+>-]<[>>+>+<<<-]>>>[<<<+>>>-]<[[-]<<[>>>+>+<<<<-]>>>>[<<<<+>>>>-]++++++++++<[>>+>+<<<-]>>>[<<<+>>>-]<[>+<-]>[<<[>>>+>+<<<<-]>>>>[<<<<+>>>>-]<[>+<<-[>>[-]>+<<<-]>>>[<<<+>>>-]<[<-[<<->>[-]]+>-]<-]<<+>]<[>>+<<-]>>[<<<[>+>+<<-]>>[<<+>>-]>-]<<[<<->>-]<[-]<[>>>>>>>>+<<<<<<<<-]>>>>>>>>>[>>]+[<<]>[>[>>]<+<[<<]>-]<<<<<<<<<<[>>+>+<<<-]>>>[<<<+>>>-]+[<+>-]<<<[-]>>[<<+>>-]<<<[>>>+>+<<<<-]>>>>[<<<<+>>>>-]++++++++++<[>>+<<-]>>[<[>>+>+<<<-]>>>[<<<+>>>-]<[>+<<-[>>[-]>+<<<-]>>>[<<<+>>>-]<[<-[<<<->>>[-]]+>-]<-]<<<+>>]<[-]<<<<[-]>>>[<<<+>>>-]<<<[>>>+>+<<<<-]>>>>[<<<<+>>>>-]<[<+>-]<]<[>+>+<<-]>>[<<+>>-]<[>+<[-]]+>[<[-]<[>>>+>+<<<<-]>>>>[<<<<+>>>>-]<[[-]>>>>>>>>[>>]<[<[<<]<<<<<+>>>>>>>[>>]<-]<-<<[<<]<<<<<>++++++++++++++++++++++++++++++++++++++++++++++++[<+>-]<.[-]<<<<[>>>>+>+<<<<<-]>>>>>[<<<<<+>>>>>-]+[<->-]<<<<<[-]>>>>[<<<<+>>>>-]<<<<[>>>>+>+<<<<<-]>>>>>[<<<<<+>>>>>-]<[<+>-]<]<[-]]<[>>++++++[<++++++++>-]<.[-]<[-]]<[-]<[-]>>>>>>>>>>>>[>[-]>]<<[-<<]<<<<<<<<<<<<<<<<<[-]<[-]";

	// converts a given lowercase string to uppercase
	// char *input_code = ",----------[----------------------.,----------]";

	// generates the bf code for printing the given input string
	// char *input_code = "+++++[>+++++++++<-],[[>--.++>+<<-]>+.->[<.>-]<<,]";

	// print_banner();

	initialize();
	process_code(input_code, 0);
	free(begin);
	return 0;
}


